//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ToDib.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TODIBTYPE                   129
#define IDD_DIALOG1                     130
#define IDC_LEFTX                       1001
#define IDC_BOTTONY                     1002
#define IDC_WIDTH                       1003
#define IDC_HEIGHT                      1004
#define IDM_SAVE_TO_DIB                 32771
#define IDM_DIB_SET                     32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
