//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Light.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_LIGHTTYPE                   129
#define IDD_COLOR_MATERIAL              130
#define IDD_LIGHT                       131
#define IDC_COLOR_RED                   1001
#define IDC_COLOR_MASK_R                1002
#define IDC_COLOR_GREEN                 1003
#define IDC_COLOR_MASK_G                1004
#define IDC_COLOR_BLUE                  1005
#define IDC_COLOR_MASK_B                1006
#define IDC_L_AMBIENT_R                 1019
#define IDC_L_AMBIENT_G                 1020
#define IDC_L_AMBIENT_B                 1021
#define IDC_L_DIFFUSE_R                 1022
#define IDC_L_DIFFUSE_G                 1023
#define IDC_L_DIFFUSE_B                 1024
#define IDC_L_SPECULAR_R                1025
#define IDC_L_SPECULAR_G                1026
#define IDC_L_SPECULAR_B                1027
#define IDC_L_POSITION_X                1028
#define IDC_L_POSITION_Y                1029
#define IDC_L_POSITION_Z                1030
#define IDC_M_AMBIENT_R                 1031
#define IDC_S_AMBIENT_R                 1031
#define IDC_M_AMBIENT_G                 1032
#define IDC_S_AMBIENT_G                 1032
#define IDC_M_AMBIENT_B                 1033
#define IDC_S_AMBIENT_B                 1033
#define IDC_M_DIFFUSE_R                 1034
#define IDC_S_DIFFUSE_R                 1034
#define IDC_M_DIFFUSE_G                 1035
#define IDC_S_DIFFUSE_G                 1035
#define IDC_M_DIFFUSE_B                 1036
#define IDC_S_DIFFUSE_B                 1036
#define IDC_M_SPECULAR_R                1037
#define IDC_S_SPECULAR_R                1037
#define IDC_M_SPECULAR_G                1038
#define IDC_S_SPECULAR_G                1038
#define IDC_M_SPECULAR_B                1039
#define IDC_S_SPECULAR_B                1039
#define IDC_M_EMISSION_R                1040
#define IDC_S_POSITION_X                1040
#define IDC_M_EMISSION_G                1041
#define IDC_S_POSITION_Y                1041
#define IDC_M_EMISSION_B                1042
#define IDC_S_POSITION_Z                1042
#define IDC_M_SHININESS                 1043
#define IDC_S_DIECTION_X                1043
#define IDC_MATERIAL_FLAG               1044
#define IDC_S_DIECTION_Y                1044
#define IDC_S_DIECTION_Z                1045
#define IDC_SPOT_CUTOFF                 1046
#define IDC_S_CONSTANT                  1054
#define IDC_S_LINEAR                    1055
#define IDC_S_QUADRATIC                 1056
#define IDC_S_ONOFF                     1057
#define IDM_CUBE                        32771
#define IDM_SPHERE                      32772
#define IDM_COLOR                       32773
#define IDM_LIGHT                       32774
#define IDM_SMOOTH_CUBE                 32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
