//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GLTrans.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_GLTRANTYPE                  129
#define IDM_CUBE                        32771
#define IDM_TRANSLATE                   32772
#define IDM_ROTATE                      32773
#define IDM_SCALE                       32774
#define IDM_CLIP                        32775
#define IDM_ASSEMBLE                    32777
#define IDM_MATRIX_STACK                32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
