//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Effect.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_EFFECTTYPE                  129
#define IDM_ALPHA_2D                    32771
#define IDM_ALPHA_3D                    32772
#define IDM_ANTI_LINE                   32773
#define IDM_ANTI_PLGN                   32774
#define IDM_FOG                         32775
#define IDM_ANTI_CUBE                   32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
