// Ring.h: interface for the Ring class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_RING_H__0738EDA5_80AB_11D2_83B3_0080C832FCF3__INCLUDED_)
#define AFX_RING_H__0738EDA5_80AB_11D2_83B3_0080C832FCF3__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

class Ring  
{
public:
	Ring();
	virtual ~Ring();

};

#endif // !defined(AFX_RING_H__0738EDA5_80AB_11D2_83B3_0080C832FCF3__INCLUDED_)
