//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Jgfz.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_JGFZTYPE                    129
#define IDM_MODEL_LENHEI                32776
#define IDM_CONTROL_STATIC              32777
#define IDM_CONTROL_MOVE                32778
#define IDM_RELATIVEMOVE_1              32779
#define IDM_TRACE_1                     32781
#define IDM_ABSOLUTEMOVEMENT            32782
#define IDM_SPEED_SLOW                  32783
#define IDM_SPEED_FAST                  32785
#define IDM_SPEED_ULTRA                 32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
