//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TwoDShape.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TWODSHTYPE                  129
#define IDM_POINTS                      32771
#define IDM_LINES                       32772
#define IDM_LINE_STRIP                  32773
#define IDM_LINE_LOOP                   32774
#define IDM_POLYGON                     32775
#define IDM_TRIANGLES                   32776
#define IDM_TRIANGLE_STRIP              32777
#define IDM_TRIANGLE_FAN                32778
#define IDM_QUADRILATERALS              32779
#define IDM_QUAD_STRIP                  32780
#define IDM_LINE_STIPPLE                32781
#define IDM_POLYGON_STIPPLE             32782
#define IDM_NONCONVEX                   32783
#define IDM_CUBE                        32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
