//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Buffer.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_BUFFERTYPE                  129
#define IDM_STENCIL_MASK                32771
#define IDM_STENCIL_CLIP                32772
#define IDM_ANTISCENE                   32773
#define IDM_NON_ANTIACCUM               32774
#define IDM_FOCUS_DEPTH                 32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
