//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CuvSufc.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CUVSUFTYPE                  129
#define IDD_DIALOG1                     130
#define IDM_BEZIER_CURVE                32771
#define IDM_EVEN_BEZIER_CUV             32772
#define IDM_NURBS_CURVE                 32773
#define IDM_BZRSUFAC_MESH               32774
#define IDM_BZRSUFAC_FILL               32775
#define IDM_BZRSUFAC_TEXTURE            32776
#define IDM_NURBSSUFAC_MESH             32777
#define IDM_NURBSSUFAC_FILL             32778
#define IDM_NURBSSUFAC_PACH             32779
#define IDM_NURBSSUFAC_TRIM             32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
