//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by matlight.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MATLIGTYPE                  129
#define IDD_LIGHT                       130
#define IDD_MATERIAL                    131
#define IDD_EDITOR                      132
#define IDD_SHINE                       133
#define IDC_EDIT2                       1006
#define IDC_SPIN1                       1007
#define IDC_EDIT3                       1008
#define IDC_SPIN2                       1009
#define IDC_EDIT4                       1010
#define IDC_SPIN3                       1011
#define IDC_EDIT5                       1012
#define IDC_SPIN4                       1013
#define IDC_EDIT6                       1014
#define IDC_SPIN5                       1015
#define IDC_EDIT7                       1016
#define IDC_SPIN6                       1017
#define IDC_EDIT8                       1018
#define IDC_SPIN7                       1019
#define IDC_EDIT9                       1020
#define IDC_SPIN8                       1021
#define IDC_EDIT10                      1022
#define IDC_SPIN9                       1023
#define IDC_EDIT11                      1024
#define IDC_SPIN10                      1025
#define IDC_EDIT12                      1026
#define IDC_SPIN11                      1027
#define IDC_EDIT13                      1028
#define IDC_SPIN12                      1029
#define IDC_SLIDER1                     1030
#define IDC_EDIT1                       1031
#define IDC_SLD_GREEN                   1032
#define IDC_SLD_BLUE                    1033
#define IDC_EDT_RED                     1036
#define IDC_EDT_GREEN                   1037
#define IDC_EDT_BLUE                    1038
#define IDC_SLD_RED                     1039
#define IDC_EDT_SHINE                   1040
#define IDC_SPN_SHINE                   1041
#define ID_EDIT_LIGHT                   32771
#define ID_EDIT_MATERIAL                32772
#define ID_LIGHT_PROP                   32773
#define ID_MAT_PROP                     32774
#define ID_BUTTON32775                  32775
#define IDS_AMBIENT                     59394
#define IDS_DIFFUSE                     59395
#define IDS_SPECULAR                    59396
#define IDS_SHINE                       59397

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
